# Site settings
title: Daniel Truong | Software Engineer
subtitle: by HTML5 UP
email: ddtruong06@gmail.com
description: Hi. I'm excited to see you here. Click below to learn more about me or check out my resume!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/daniel-d-truong
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/daniel-d-truong
pinterest_url:
slack_url:
twitter_url: 
email: ddtruong06@gmail.com

# Build settings
markdown: kramdown

sass:
  style: compressed

theme: jekyll-theme-minimal